
# module.exports = {
#   amazon:
#   service: S3
#   access_key_id: "process.env.AWS_ACCESS_KEY_ID"
#   secret_access_key: "process.env.AWS_SECRET_ACCESS_KEY"
#   region: "Asia Pacific (Sydney) ap-southeast-2"
#   bucket: "process.env.S3_BUCKET"
# }